spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:40320/railway
    username: postgres
    password: cF3a-2acdffAc2335Cf362BFfAdbF*C3
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create